name: sink
description: Easily verify that you&#x27;re spending more than you can afford

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.7.4
  cupertino_icons: ^0.1.0
  flutter_redux: ^0.5.1
  intl: ^0.15.6
  uuid: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true