name: sink
description: Easily verify that you&#x27;re spending more than you can afford

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.9.5+2
  flutter_redux: ^0.5.2
  charts_flutter: ^0.5.0
  intl: ^0.15.6
  uuid: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.5.1

flutter:
  uses-material-design: true